services:
  postgres:
    image: postgres:16
    container_name: vacancy-parser
    environment:
      POSTGRES_DB: vacancy-parser
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: